# Generated by Django 4.1 on 2022-08-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(default=[], verbose_name='Permissions')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('serverID', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('displayName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
