# Generated by Django 4.1 on 2022-08-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptika', '0005_alter_role_permissions_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.TextField(default=''),
        ),
    ]
