# Generated by Django 4.1 on 2022-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptika', '0007_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='action',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='action_log_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='server_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
